# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_remove_product_order'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
