# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20171107_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order']},
        ),
    ]
